### ISSUE TITLE
Question: Should SMTP_FROM override the from of relayed emails?

### ISSUE THREAD

**Issue by Smuerdt** [crazy-max/docker-msmtpd#23]
Hey, I am successfully using this image to relay emails and I was wondering what the exact behavior of the `SMTP_FROM` variable is in this case. From what I understood it should overwrite the `from` of all incoming mails before relaying them to `SMTP_HOST`. Unfortunately thats not the case for me. The original `from` is just untouched. Am I doing something wrong, or do I need to enable the replacement of `from` separately?

P.S.: Thanks for this great image I really enjoy the simplicity of it.

**Comment by crazy-max** [comment]
@Smuerdt Sorry for the delay

>  I was wondering what the exact behavior of the `SMTP_FROM` variable is in this case. From what I understood it should overwrite the `from` of all incoming mails before relaying them to `SMTP_HOST`.

The envelope-from address will be set if the mail does not have one because [`set_from_header` default to `auto`](https://marlam.de/msmtp/msmtp.html#Envelope_002dfrom-address). I will add an option to be able to change that.

> P.S.: Thanks for this great image I really enjoy the simplicity of it.

Thanks, that's why I created it. I wanted something simple and powerful.

**Comment by crazy-max** [comment]
@Smuerdt https://github.com/crazy-max/docker-msmtpd/releases/tag/1.8.15-r2
